WeFix.WebUI/Controllers/DepartmentManagersController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using WeFix.WebUI.Models;
using WeFix.Domain.Entities;
using WeFix.Domain.Context;
using System;
using System.Net;
using System.IO;
using System.Drawing;
using System.Data.Entity;

namespace WeFix.WebUI.Controllers
{
    /// <summary>
    /// The department manager controller provide the business logic to add, edit, delete and view managers
    /// </summary>
    /// <remarks>
    /// In most cases the controller interacts with the Organisations Dashboard so that organisation managers have the ability to CRUD their Department Managers
    /// </remarks>
    public class DepartmentManagersController : Controller
    {
        private SignInManager _signInManager;
        private UserManager _userManager;
        private EFDbContext db = new EFDbContext();
        private const string ExpectedImagePrefixJpeg = "data:image/jpeg;base64,";
        private const string ExpectedImagePrefixPng = "data:image/png;base64,";

        public DepartmentManagersController()
        {
        }

        public DepartmentManagersController(UserManager userManager, SignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public SignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<SignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public UserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<UserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: DepartmentManagers
        public ActionResult Index()
        {
            var departmentManagers = db.DepartmentManagers.Include(d => d.Department).Include(d => d.User);
            return View(departmentManagers.ToList());
        }

        // GET: DepartmentManagers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            DepartmentManager departmentManager = db.DepartmentManagers.Find(id);
            if (departmentManager == null)
            {
                return HttpNotFound();
            }
            return View(departmentManager);
        }

        // GET: DepartmentManagers/Create
        public ActionResult Create()
        {
          
            return View();
        }

        // POST: DepartmentManagers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentManagerId,UserId,DepartmentId,Position")] WeFix.WebUI.Models.DashboardViewModel departmentManager, FormCollection collection)
        {
            try
            {
                int deptId = Convert.ToInt32(collection.Get("deptId"));
                string userId = Convert.ToString(collection.Get("ManagerUserId"));
                DepartmentManager deptMan = new DepartmentManager()
                {
                     DepartmentId =deptId,
                      Position = departmentManager.Position,
                       UserId = userId                                           
                };
                db.DepartmentManagers.Add(deptMan);
                db.SaveChanges();
                return RedirectToAction("Management","Organisations",null);
            }
            catch
            {
                return RedirectToAction("Management", "Organisations", null);
            }                  
            
        }

        // GET: DepartmentManagers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            DepartmentManager departmentManager = db.DepartmentManagers.Find(id);
            if (departmentManager == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", departmentManager.DepartmentId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", departmentManager.UserId);
            return View(departmentManager);
        }

        // POST: DepartmentManagers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentManagerId,UserId,DepartmentId,Position")] DepartmentManager departmentManager)
        {
            if (ModelState.IsValid)
            {
                db.Entry(departmentManager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Management","Organisations",null);
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", departmentManager.DepartmentId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", departmentManager.UserId);
            return View(departmentManager);
        }

        // GET: DepartmentManagers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            DepartmentManager departmentManager = db.DepartmentManagers.Find(id);
            if (departmentManager == null)
            {
                return HttpNotFound();
            }
            return View(departmentManager);
        }

        // POST: DepartmentManagers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DepartmentManager departmentManager = db.DepartmentManagers.Find(id);
            db.DepartmentManagers.Remove(departmentManager);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteFromDash(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            DepartmentManager departmentManager = db.DepartmentManagers.Find(id);
            if (departmentManager == null)
            {
                return HttpNotFound();
            }
            User user = db.Users.Find(departmentManager.UserId);
            db.DepartmentManagers.Remove(departmentManager);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Management", "Organisations", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateWithUser(DashboardViewModel model, FormCollection collection)
        {
            try
            {
                string code = collection.Get("CountryCode");
                string cell = string.Empty;
                if (model.Cell.StartsWith("0"))
                {
                    cell = code + model.Cell.Substring(0, 1);
                }else
                {
                    cell = code + model.Cell;
                }
                var user = new User
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Cell = cell,
                    PhoneNumber = cell,
                    IsManager = true,
                    ConnectionId ="",
                    EmailConfirmed =true,
                    IsOnline =false,
                    LastOnline =DateTime.Now,
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    string data_uri = collection.Get("base64");
                    string userId = string.Empty;
                    while (userId == string.Empty)
                    {
                        userId = (from x in db.Users where x.Id == user.Id select x.Id).FirstOrDefault();
                    }

                    User newUser = (from x in db.Users where x.Id == userId select x).FirstOrDefault();
                    DepartmentManager deptManager = new DepartmentManager()
                    {
                        DepartmentId = model.DepartmentId,
                        Position = model.Position,
                        UserId = newUser.Id
                    };
                    db.DepartmentManagers.Add(deptManager);
                    
                    if (data_uri != "")
                    {
                        string Base64 = string.Empty;
                        if (data_uri.Contains(ExpectedImagePrefixJpeg))
                        {
                            Base64 = data_uri.Substring(ExpectedImagePrefixJpeg.Length);
                        }
                        else
                        {

WeFix.WebUI/Views/DepartmentManagers/Create.cshtml
@model WeFix.Domain.Entities.DepartmentManager

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepartmentManager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WeFix.WebUI/Views/DepartmentManagers/Delete.cshtml
@model WeFix.Domain.Entities.DepartmentManager

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DepartmentManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WeFix.WebUI/Views/DepartmentManagers/Details.cshtml
@model WeFix.Domain.Entities.DepartmentManager

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}
<div>
    <h4>Department Manager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DepartmentManagerId }) |
    @Html.ActionLink("Back to List", "Management","Organisations")
</p>

WeFix.WebUI/Views/DepartmentManagers/Edit.cshtml
@model WeFix.Domain.Entities.DepartmentManager

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentManagerId)

        <div class="form-group">
            <label for="UserDrop" class="col-sm-2 control-label">User</label>
            <div class="col-sm-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control", @style="UserDrop" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="DepartmentText" class="col-sm-2 control-label">Department</label>
            <div class="col-sm-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control",@id="DepartmentText" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Management","Organisations",null,new { @class="btn btn-flat btn-guardian" })
</div>

WeFix.WebUI/Views/DepartmentManagers/Index.cshtml
@model IEnumerable<WeFix.Domain.Entities.DepartmentManager>
@{
    var db = new WeFix.Domain.Context.EFDbContext();
}
<p>
    <a href="#" onclick="CreateDepartmentManager()" class="btn btn-flat btn-primary">Create New</a>
</p>
<hr/>
<div class="row">
    @foreach (var item in Model)
    {
        var dept = db.Departments.Find(item.DepartmentId);
        var category = (from x in db.Categories where x.CategoryId == dept.CategoryId select x).FirstOrDefault();
        var User = db.Users.Find(item.UserId);
        <div class="col-sm-6" style="border: 3px solid #E6E6FA; border-radius:5px;">
            <!-- Post -->
            <div class="post">
                <div class="user-block">                  
                    <img class="img-circle img-bordered-sm" src="~/Content/img/@category.Image" alt="user image">                          
                    <span class="username">
                        <a href="#">@User.FirstName @User.LastName</a>
                       
                            <a onclick="ConfirmManagerDelete(@item.DepartmentManagerId)" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                                          
                    </span>
                    <span class="description">Department - @item.Department.Name</span>
                    <span class="description">Position - @item.Position</span>
                </div>
                <!-- /.user-block -->
                <ul class="list-inline">
                    <li><a href="#" onclick="location.href='@Url.Action("Edit","DepartmentManagers",new { id = item.DepartmentManagerId })'" class="link-black text-sm"><i class="fa fa-edit margin-r-5"></i> Edit</a></li>
                    <li>
                        <a href="#" onclick="location.href='@Url.Action("Details","DepartmentManagers",new { id = item.DepartmentManagerId })'" class="link-black text-sm"><i class="fa fa-info margin-r-5"></i> Details</a>
                    </li>            
                </ul>
            </div>
            <!-- /.post -->
        </div>
    }
</div>
<script type="text/javascript">
    function ConfirmManagerDelete(id) {
        var r = confirm("Are you sure you want to delete this Manager?")
        if (r == true) {
            location.href = '/DepartmentManagers/DeleteFromDash/' + id;
        }
    }
</script>
 