WeFix.WebUI/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WeFix.Domain.Context;
using WeFix.Domain.Entities;
using GoogleMaps.LocationServices;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace WeFix.WebUI.Controllers
{
    public class DepartmentsController : Controller
    {
        private EFDbContext db = new EFDbContext();

        // GET: Departments
        public ActionResult Index()
        {
            var departments = db.Departments.Include(d => d.Category).Include(d => d.Organisation);
            return View(departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create(int? id)
        {
            //ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,Name,AddressLine1,AddressLine2,City,Country,PostalCode,CategoryId,OrganisationId")] WeFix.WebUI.Models.DashboardViewModel department, FormCollection collection)
        {
            int orgId = Convert.ToInt32(collection.Get("OrgId"));
            AddressData address = new AddressData()
            {
                Address = department.AddressLine1 + ", " + department.AddressLine2,
                City = department.City,
                Country = department.Country,
                Zip = department.PostalCode,
                State = ""
            };
            GoogleLocationService gls = new GoogleLocationService();
            var latlng = gls.GetLatLongFromAddress(address);
            //var juris = Convert.ToDecimal("jurisdiction");
            Department dept = new Department()
            {
                AddressLine1 = department.AddressLine1,
                AddressLine2 = department.AddressLine2,
                CategoryId = department.CategoryId,
                City = department.City,
                Country = department.Country,
                Latitude = latlng.Latitude,
                Longitude = latlng.Longitude,
                Name = department.Name,
                OrganisationId = orgId,
                PostalCode = department.PostalCode
            };
            try
            {
                db.Departments.Add(dept);
                db.SaveChanges();
                return RedirectToAction("Management","Organisations",null);
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        public ActionResult Management()
        {
            var userID = HttpContext.User.Identity.GetUserId();
            var manager = (from x in db.DepartmentManagers where x.UserId == userID select x).FirstOrDefault();
            if (manager == null)
            {
                ViewBag.Error = "You are not a department manager";
                return RedirectToAction("Index", "Home", null);
            }
            else
            {
                return View();
            }            
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", department.CategoryId);
            ViewBag.OrganisationId = new SelectList(db.Organisations, "OrganisationId", "Name", department.OrganisationId);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentId,Name,AddressLine1,AddressLine2,City,Country,PostalCode,CategoryId,OrganisationId")] Department department, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                int orgId = 0;
                orgId = Convert.ToInt32(collection.Get("OrgId"));
                department.OrganisationId = orgId;
                var gls = new GoogleLocationService();
                AddressData address = new AddressData()
                {
                    Address = department.AddressLine1 + "' " + department.AddressLine2,
                    City = department.City,
                    Country = department.Country,
                    State = "",
                    Zip = department.PostalCode
                };
                var latlng = gls.GetLatLongFromAddress(address);
               
                    department.Latitude = Convert.ToDouble(latlng.Latitude, CultureInfo.InvariantCulture);
                    department.Longitude = Convert.ToDouble(latlng.Longitude, CultureInfo.InvariantCulture);
                

                var jurisdiction = Convert.ToDecimal(collection.Get("jurisdiction"));

                department.Jurisdiction = jurisdiction;

                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Management","Organisations",null);
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", department.CategoryId);
            ViewBag.OrganisationId = new SelectList(db.Organisations, "OrganisationId", "Name", department.OrganisationId);
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error500", "Home", null);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteFromDash(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Management","Organisations",null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WeFix.WebUI/Controllers/FaultsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WeFix.Domain.Context;
using WeFix.Domain.Entities;
using WeFix.Logic;

namespace WeFix.WebUI.Controllers
{
    /// <summary>
    /// This controller performs the CRUD functionality for reporting faults
    /// </summary>
    /// <remarks>
    /// Due to the use of javascript, the use of FormCollection get values from hidden inputs in the View
    /// </remarks>
    public class FaultsController : Controller
    {
        private EFDbContext db = new EFDbContext();
        /// <summary>
        /// Constant used to remove the unnecessary string in the base64 string grabbed from the file upload
        /// </summary>
        private const string ExpectedImagePrefixJpeg = "data:image/jpeg;base64,";
        private const string ExpectedImagePrefixPng = "data:image/png;base64,";

        /// <summary>
        /// Get View if user exists
        /// </summary>
        /// <returns>
        /// View 'ReportFault'
        /// </returns>
        public ActionResult ReportFault()
        {
            var userId = HttpContext.User.Identity.GetUserId();
            var user = (from x in db.PublicUsers where x.UserId == userId select x.UserId).FirstOrDefault();
            ViewBag.UserId = user;
            if (user != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Manage", null);
            }
        }
        /// <summary>
        /// The main function of the app, to create a fault that will be emailed to the organisation managers
        /// </summary>
        /// <param name="fault">Fault Object Populated from View</param>
        /// <param name="collection">FormCollection to grab values from hidden inputs</param>
        /// <returns>
        /// Fault
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReportFault([Bind(Include = "Description")] Fault fault, FormCollection collection)
        {
            //Get Latitude from hidden input of name='latitude'
            string lat = collection.Get("latitude");
            //Get Longitude value from hidden input of name='longitude'
            string lng = collection.Get("longitude");
            //Get the id of the logged on user
            string guid = HttpContext.User.Identity.GetUserId();
            //Since only public users may report faults, get an object of type PublicUser
            PublicUser user = (from x in db.PublicUsers where x.UserId == guid select x).FirstOrDefault();

            if (user != null)
            {
                /*-----------Add LatLng to Model-----------------*/
                //Due to some computer systems using commas instead of periods for decimal points
                //Therefore, check to see if "," exists. If so, replace with a period
                if (lat.Contains(","))
                {
                    lat.ToString().Replace(",", ".");
                    lng.ToString().Replace(",", ".");
                    //add values to the fault object. Data type must be double for best results for geolocation
                    //On a side note, no idea why I had to include CultureInfo, it works this way so fuck it.
                    fault.Latitude = Convert.ToDouble(lat, CultureInfo.InvariantCulture);
                    fault.Longitude = Convert.ToDouble(lng, CultureInfo.InvariantCulture);
                }
                else
                {
                    //Since we are dealing with periods, just add the values as is
                    fault.Latitude = Convert.ToDouble(lat, CultureInfo.InvariantCulture);
                    fault.Longitude = Convert.ToDouble(lng, CultureInfo.InvariantCulture);
                }

                /*---------Add Public User Id and Date Created-----------*/
                fault.PublicUserId = user.PublicUserId;
                fault.DateCreated = DateTime.Now;

                /*----------Add Category Id and Manager Id---------------*/
                //get category ID from formcollection with name="CategoryId"
                int categoryId = Convert.ToInt32(collection.Get("CategoryId"));
                fault.CategoryId = categoryId;

                /*------------Add Severity Id----------------------------*/
                //get severity level from formcollection with name="SeveritySlider"
                int SeverityLevel = Convert.ToInt32(collection.Get("SeveritySlider"));
                fault.SeverityId = SeverityLevel;

                /*----------------Add Upload image here------------------*/
                //So this was hard. Using HttpPostedFileBase should have worked. But no.
                //So I learnt that base64 string can can be grabbed from javascript and appended to
                //an hidden input where I grabbed in from the formcollection
                string data_uri = collection.Get("base64Label");
                //check that base64 is not null, else do not add to fault. It is nullable
                if (data_uri != "")
                {
                    //Remove the prefix from the base 64 string
                    string base64 = string.Empty;
                    if (data_uri.Contains(ExpectedImagePrefixJpeg))
                    {
                        base64 = data_uri.Substring(ExpectedImagePrefixJpeg.Length);
                    }
                    else
                    {
                        base64 = data_uri.Substring(ExpectedImagePrefixPng.Length);
                    }
                    //convert to byte array
                    byte[] bytes = Convert.FromBase64String(base64);
                    //declare the directory where the resulting image will be saved
                    string directory = "~/Content/img/faults/" + user.PublicUserId + "/";
                    
                    //Create the image object that will be the image
                    //Create the image object that will be the image
                    Image image;
                    Image thumbnail;
                    //Use MemoryStream to read byte array
                    using (MemoryStream ms = new MemoryStream(bytes))
                    {
                        //create the image
                        image = Image.FromStream(ms);
                        thumbnail = Image.FromStream(ms);
                        var imageRectangle = new Rectangle(0, 0, 85, 85);
                        var bitmapVersion = new Bitmap(image);
                        bitmapVersion = bitmapVersion.Clone(imageRectangle,PixelFormat.DontCare);
                        //Make sure that the directory where the image is to be store actually exists;
                        if (Directory.Exists(directory))
                        {
                            //We need a unique directory for the image. So I've used the public users ID and The date created
                            string date = (fault.DateCreated.Day.ToString() + fault.DateCreated.Month.ToString() + fault.DateCreated.Year.ToString() + fault.DateCreated.TimeOfDay.ToString().Replace(":", "")).Replace(".", "");
                            //Save the image to directory
                            image.Save(Server.MapPath(directory + date + ".jpg"),ImageFormat.Jpeg);
                            bitmapVersion.Save(Server.MapPath(directory + date + ".png"), ImageFormat.Png);
                            //Its called Mime type, buts just the URL where the image is located
                            fault.ImageURL = directory.Replace("~", "") + date + ".jpg";
                            fault.ImageThumbnail = directory.Replace("~", "") + date + ".png";
                        }
                        else
                        {
                            string date = fault.DateCreated.Day.ToString() + fault.DateCreated.Month.ToString() + fault.DateCreated.Year.ToString() + fault.DateCreated.TimeOfDay.ToString().Replace(":", "");
                            //Directory does not exist so damn well create it
                            Directory.CreateDirectory(Server.MapPath(directory));
                            image.Save(Server.MapPath(directory + date + ".jpg"),ImageFormat.Jpeg);
                            bitmapVersion.Save(Server.MapPath(directory + date + "..png"),ImageFormat.Png);
                            fault.ImageURL = directory.Replace("~", "") + date + ".jpg";
                            fault.ImageThumbnail = directory.Replace("~", "") + date + ".png";
                        }
                    }
                }
                /*-------------Add Sub-category------------------------*/
                //Get sub-category from formcollection with name='subCatId'
                int subCatId = Convert.ToInt32(collection.Get("subCatId"));
                //Sub-category is nullable so only add if it exists
                if (subCatId != 0)
                {
                    fault.SubCategoryId = subCatId;
                }
                /*-------------Add Progress Bools--------------*/
                fault.NotStarted = true;
                fault.InProgress = false;
                fault.Resolved = false;
                /*-------------Increment Count of Category Used--------------------------*/
                Category category = db.Categories.Find(fault.CategoryId);
                int count = category.Count + 1;
                category.Count = count;

                /*------------Save changes to Database-----------------*/
                try
                {
                    db.Faults.Add(fault);
                    db.Entry(category).State = EntityState.Modified;
                    db.SaveChanges();

WeFix.WebUI/Views/Faults/DeptIndex.cshtml
@model IEnumerable<WeFix.Domain.Entities.Fault>

@using WeFix.Logic
@using WeFix.Domain.Context
@using GoogleMaps.LocationServices
@{
    var helper = new Helpers();
    var db = new EFDbContext();
    var gls = new GoogleLocationService();
}
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-4" style="border: 3px solid #E6E6FA; border-radius:5px;">
            <!-- Post -->
            <div class="post">
                <div class="user-block">
                    @if (item.ImageURL != null)
                    {
                        <img class="img-circle img-bordered-sm" src="@item.ImageURL.Replace("~","../..")" alt="user image">
                    }
                    <span class="username">
                        <a href="#">@item.FaultId</a>
                    </span>
                    <span class="description"><strong>Date</strong> @item.DateCreated</span>
                    <span class="description"><strong>Category</strong> @item.Category.Name</span>
                    <span class="description"><strong>Sub-Category</strong> @if (item.SubCategory != null)
                    { <text>@item.SubCategory.Name</text>}</span>
                    <span class="description"><strong>Severity</strong> @item.SeverityId</span>
                </div>
                <!-- /.user-block -->
                <p>
                    @{ var address = helper.GetAddressFromLatLong(item.Latitude, item.Longitude);}
                    <strong>Address:</strong> @address
                </p>
                <p>
                    <strong>Description:</strong> @item.Description
                </p>
                @if (item.ManagerId != null)
                {
                    var departmentManager = db.DepartmentManagers.Find(item.ManagerId);
                    var user = db.Users.Find(departmentManager.UserId);
                    <p>
                        @Html.ActionLink(user.LastName + ", " + user.FirstName, "UnAssignManager", "Organisations", new { id = item.FaultId }, new { @title = "Unassign Manager", @class = "btn btn-flat btn-success" })
                    </p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Assign", "AssignManager", "Organisations", new { id = item.FaultId }, new { @class = "btn btn-flat btn-primary", @title = "Assign Manager" })
                    </p>
                }
                @if (item.Resolved)
                {
                    <p>
                        @Html.ActionLink("Mark Unresolved", "MarkUnresolved", "Faults", new { id = item.FaultId }, new { @class = "btn btn-falt btn-danger" })
                    </p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Mark Resolved", "MarkResolved", "Faults", new { id = item.FaultId }, new { @class = "btn btn-success" })
                    </p>
                }
                <ul class="list-inline">
                    <li>
                        <a href="#" onclick="location.href='@Url.Action("Details","Faults",new { id = item.FaultId })'" class="link-black text-sm"><i class="fa fa-info margin-r-5"></i> Details</a>
                    </li>
                </ul>
            </div>
            <!-- /.post -->
        </div>
                        }
</div>

WeFix.WebUI/Views/Faults/Details.cshtml
@model WeFix.Domain.Entities.Fault
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}
@using WeFix.Logic
@using WeFix.Domain.Context
@using GoogleMaps.LocationServices
@{
    var helper = new Helpers();
    var db = new EFDbContext();
    var gls = new GoogleLocationService();
}
<div style="border: 3px solid #E6E6FA; border-radius:5px; z-index:5;position:relative;height:auto;background-color:#fff; margin-left:25px;margin-right:25px;margin-top:150px;">
    <!-- Post -->
    <div class="post">
        <div class="user-block">
            @if (Model.ImageURL != null)
            {
                <img class="img-circle img-bordered-sm" src="@Model.ImageURL.Replace("~","../..")" alt="user image">
            }
            <span class="username">
                <a href="#">@Model.FaultId</a>
                <a href="#" onclick="location.href='@Url.Action("DeleteFromDash", "Departments",new { id=Model.FaultId})'" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
            </span>
            <span class="description"><strong>Date</strong> @Model.DateCreated</span>
            <span class="description"><strong>Category</strong> @Model.Category.Name</span>
            <span class="description"><strong>Sub-Category</strong> @Model.SubCategory.Name</span>
            <span class="description"><strong>Severity</strong> @Model.SeverityId</span>
        </div>
        <!-- /.user-block -->
        <p>
            @{ var address = helper.GetAddressFromLatLong(Model.Latitude, Model.Longitude);}
            <strong>Address:</strong> @address
        </p>
        <p>
            <strong>Description:</strong> @Model.Description
        </p>
        <p>
            <strong>LatLng:</strong> @(Model.Latitude + "||" + Model.Longitude)
        </p>
       @if (Model.ManagerId != null)
       {
           var departmentManager = db.DepartmentManagers.Find(Model.ManagerId);
           var user = db.Users.Find(departmentManager.UserId);
        <p>
            @Html.ActionLink(user.LastName + ", " + user.FirstName, "UnAssignManagerIfInDetails", "Organisations", new { id = Model.FaultId }, new { @title = "Unassign Manager", @class = "btn btn-flat btn-success" })
        </p>
       }
       else
       {
        <p>
            @Html.ActionLink("Assign", "AssignManagerIfInDetails", "Organisations", new { id = Model.FaultId }, new { @class = "btn btn-flat btn-primary", @title = "Assign Manager" })
        </p>
       }
    @if (Model.Resolved)
    {
        <p>
            @Html.ActionLink("Mark Unresolved", "MarkUnresolvedIfInDetails", "Faults", new { id = Model.FaultId }, new { @class = "btn btn-falt btn-danger" })
        </p>
    }
    else
    {
        <p>
            @Html.ActionLink("Mark Resolved", "MarkResolvedIfInDetails", "Faults", new { id = Model.FaultId }, new { @class = "btn btn-success" })
        </p>
    }
    <ul class="list-inline">
        <li>
            <a href="#" onclick="location.href='@Url.Action("Management","Organisations",new { id = Model.FaultId })'" class="link-black text-sm"><i class="fa fa-arrow-circle-left margin-r-5"></i> Back Management</a>
        </li>
    </ul>
    </div>
    <!-- /.post -->
</div>

WeFix.WebUI/Views/Faults/DetailsForPublic.cshtml
@model WeFix.Domain.Entities.Fault

@{
    ViewBag.Title = "DetailsForPublic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using WeFix.Logic
@using WeFix.Domain.Context
@using GoogleMaps.LocationServices
@{
    var helper = new Helpers();
    var db = new EFDbContext();
    var gls = new GoogleLocationService();
}
<div style="border: 3px solid #E6E6FA; border-radius:5px; z-index:5;position:relative;height:auto;background-color:#fff; margin-left:25px;margin-right:25px;margin-top:150px;">
    <!-- Post -->
    <div class="post">
        <div class="user-block">
            @if (Model.ImageURL != null)
            {
                <img class="img-circle img-bordered-sm" src="@Model.ImageURL.Replace("~","../..")" alt="user image">
            }
            <span class="username">
                <a href="#">@Model.FaultId</a>
                    <a href="#" onclick="checkDelete()" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                
                
            </span>
            <span class="description"><strong>Date</strong> @Model.DateCreated</span>
            <span class="description"><strong>Category</strong> @Model.Category.Name</span>
            <span class="description"><strong>Sub-Category</strong> @Model.SubCategory.Name</span>
            <span class="description"><strong>Severity</strong> @Model.SeverityId</span>
        </div>
        <!-- /.user-block -->
        <p>
            @{ var address = helper.GetAddressFromLatLong(Model.Latitude, Model.Longitude);}
            <strong>Address:</strong> @address
        </p>
        <p>
            <strong>Description:</strong> @Model.Description
        </p>
        <ul class="list-inline">
            <li>
                <a href="#" onclick="location.href='@Url.Action("Edit","Faults",new { id = Model.FaultId })'" class="link-black text-sm"><i class="fa fa-edit margin-r-5"></i> Edit</a>
               
            </li>
            <li class="pull-right">
                @if (Model.ManagerId != null)
                {
                    var departmentManager = db.DepartmentManagers.Find(Model.ManagerId);
                    var user = db.Users.Find(departmentManager.UserId);
                    <div>
                        Assigned to @(user.LastName + ", " + user.FirstName)
                    </div>
                }
                else
                {
                    <div>
                        Unassigned
                    </div>
                }
            </li>
            <li class="pull-right">
                @if (Model.Resolved)
                {
                    <div>
                        Resolved
                    </div>
                }
                else
                {
                    <div>
                        Unresolved
                    </div>
                }
            </li>
        </ul>
    </div>
    <!-- /.post -->
</div>

<script type="text/javascript">
    function checkdelete() {
        var r = confirm("Are you sure you want to delete this fault report?")
        if (r == true) {
            location.href='@Url.Action("","",new { id=Model.FaultId })';
        }
    }

</script>

WeFix.WebUI/Views/Faults/OrgIndex.cshtml
@model IEnumerable<WeFix.Domain.Entities.Fault>

@using WeFix.Logic
@using WeFix.Domain.Context
@using GoogleMaps.LocationServices
@{ 
    var helper = new Helpers();
    var db = new EFDbContext();
    var gls = new GoogleLocationService();
}
<div class="row">
@foreach (var item in Model)
{
    <div class="col-sm-4" style="border: 3px solid #E6E6FA; border-radius:5px;">
    <!-- Post -->
    <div class="post">
        <div class="user-block">
            @if (item.ImageURL != null)
            {
                <img class="img-circle img-bordered-sm" src="@item.ImageURL.Replace("~","../..")" alt="user image">
            }            
            <span class="username">
                <a href="#">@item.FaultId</a>
            </span>
            <span class="description"><strong>Date</strong> @item.DateCreated</span>
            <span class="description"><strong>Category</strong> @item.Category.Name</span>
            <span class="description"><strong>Sub-Category</strong> @if (item.SubCategory != null) { <text>@item.SubCategory.Name</text>}</span>
            <span class="description"><strong>Severity</strong> @item.SeverityId</span>          
        </div>
        <!-- /.user-block -->
        <p>
            @{ var address = helper.GetAddressFromLatLong(item.Latitude, item.Longitude);}
            <strong>Address:</strong> @address
        </p>
        <p>
            <strong>Description:</strong> @item.Description
        </p>
        @if (item.ManagerId != null)
                {
                    var departmentManager = db.DepartmentManagers.Find(item.ManagerId);
                    var user = db.Users.Find(departmentManager.UserId);
            <p>
                @Html.ActionLink(user.LastName + ", " + user.FirstName, "UnAssignManager", "Organisations", new { id = item.FaultId }, new { @title = "Unassign Manager", @class = "btn btn-flat btn-success" })
            </p>
        }
        else
        {
            <p>
                @Html.ActionLink("Assign", "AssignManager", "Organisations", new { id = item.FaultId }, new { @class = "btn btn-flat btn-primary", @title = "Assign Manager" })
            </p>
        }
        @if (item.Resolved)
                {
            <p>
                @Html.ActionLink("Mark Unresolved", "MarkUnresolved", "Faults", new { id = item.FaultId }, new { @class = "btn btn-falt btn-danger" })
            </p>
        }
        else
        {
            <p>
                @Html.ActionLink("Mark Resolved", "MarkResolved", "Faults", new { id = item.FaultId }, new { @class = "btn btn-success" })
            </p>
        }
        <ul class="list-inline">
            <li>
                <a href="#" onclick="location.href='@Url.Action("Details","Faults",new { id = item.FaultId })'" class="link-black text-sm"><i class="fa fa-info margin-r-5"></i> Details</a>
            </li>           
        </ul>
    </div>
    <!-- /.post -->
        </div>
                }
 </div>